### ISSUE TITLE
Question about face swap metrics.

### ISSUE THREAD

**Issue by w-yibo** [FaceAdapter/Face-Adapter#15]
Thanks for your awesome work! I wonder know how do you compute the merics of face swap, cound you provide the code or other github repo?

**Comment by KeepNoob** [comment]
Hi, I come with the same problem, have you solved it yet?
I tried to compute the cosine similarity for the net_arcface output, but the output shape of net_arcface is [1,64,512] which cannot be put into Cosine Similarity whatever implemented by torch.nn or TorchMetrics.
